pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devops-web:latest -f docker/Dockerfile .'
      }
    }

    stage('Deploy') {
      steps {
        sh '''
        docker stop devops-web || true
        docker rm devops-web || true
        docker run -d -p 8091:80 --name devops-web devops-web:latest
        '''
      }
    }
  }
}
