pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t devops-web:latest -f docker/Dockerfile .'
      }
    }

    stage('Deploy with Ansible') {
      steps {
       sh 'sudo ansible-playbook -i ansible/inventory.ini ansible/playbook.yml'
      }
    }
  }
}
