- name: Deploy web contrainer using Docker
  host: web
  become: true

  tasks:
    - name: Stop old contrainer if exits
      shell: docker stop devops-web || true

    - name: Remove old contrainer if exits
      shell: docker rm devops-web || true

    - name: Run new contrainer
      shell: >
        docker run -d
        -p 8091:80
        --name devops-web
        devops-web:latest