---
- name: Deploy web container using Docker
  hosts: web
  gather_facts: false

  tasks:
    - name: Deploy Container (Auto stop, remove and run)
      community.docker.docker_container:
        name: devops-web
        image: devops-web:latest
        state: started
        restart: yes
        recreate: yes
        published_ports:
          - "8091:80"